import ps from ".";

const content = [
  {
    key: 1,
    title: "useEffect 무한루프",
    body: "이 블로그를 만들면서 useEffect를 사용했는데 렌더링이 계속 일어나 사이트가 다운됐었다 useEffect(함수,[종속성]) useEffect는 종속성이 변했을 때 useEffect 내부에 있는 함수를 실행시키는 역할을 한다. 자꾸 렌더링이 일어나는 이유를 찾아보니 함수부분에 setState를 하고 종속성에 state 값을 넣어줘서 그런거였다.",
    date: "2022.09.13",
    category: "react",
    link: "useEffect-infinite-loop",
    element: <ps.UseEffectInfiniteLoop />,
  },
  {
    key: 2,
    title: "React-router 404 not found",
    body: "문제발생 블로그에 댓글 기능을 추가하고 싶어 Giscus을 알아보고 바로 블로그에 적용을 한 후 잘 동작하나 확인을 하던 와중 갑자기 404 페이지가 떠서 아주 놀랐던 기억이 있다. react-router를 사용할때 이동페이시에서 새로고침을 했을 때 생기는 문제였다. 이유 React 는 CSR(클라이언트 사이트 렌더링)이다. 이를 React-Router 로 Path를",
    date: "2022.09.13",
    category: "react",
    link: "router-404",
    element: <ps.Router404 />,
  },
  {
    key: 3,
    title: "백준 1712번 알고리즘 [node.js]",
    body: "첫 줄에 A, B, C 가 주어지는데 A는 고정비용 B는 가변비용 C는 판매가격이라고 할 때 최초로 총 수입이 총 비용보다 많아져 이익이 발생하는 손익분기점을 넘기는 값을 구하는 문제이다  간단하게 생각해서 마진은 판매가격에서 가변비용을 빼주게 되면 나온다. 이 마진을 고정비용으로 나눠주게 되면 손익분기점이 나오는데 ",
    date: "2022.12.01",
    category: "백준 문제풀이",
    link: "BJ1712",
    element: <ps.BJ1712 />,
  },
  {
    key: 4,
    title: "백준 2292번 알고리즘 [node.js]",
    body: "육각형으로 이루어진 벌집이 있다. 중앙에 방 1부터 시작해서 이웃하는 방에 돌아가면서 1찍 증가하는 번주를 매기는데 숫자 N이 주어졌을 떄, 벌집의 중앙 1에서 N번 방까지 최소 개수의 방을 지나서 갈때 몇개의 방을 지나가는지(시작과 끝을 포함)를 계산하는 문제이다. 예를 들어 13까지는 3개, 58까지는 5개를 지난다.",
    date: "2022.12.12",
    category: "백준 문제풀이",
    link: "BJ2292",
    element: <ps.BJ2292 />,
  },
  {
    key: 5,
    title: "백준 4344번 알고리즘 [node.js]",
    body: "육각형으로 이루어진 벌집이 있다. 중앙에 방 1부터 시작해서 이웃하는 방에 돌아가면서 1찍 증가하는 번주를 매기는데 숫자 N이 주어졌을 떄, 벌집의 중앙 1에서 N번 방까지 최소 개수의 방을 지나서 갈때 몇개의 방을 지나가는지(시작과 끝을 포함)를 계산하는 문제이다. 예를 들어 13까지는 3개, 58까지는 5개를 지난다.",
    date: "2022.12.21",
    category: "백준 문제풀이",
    link: "BJ4344",
    element: <ps.BJ4344 />,
  },
  {
    key: 6,
    title: "Fragment에 대해 알아보자",
    body: "리엑트에서 컴포넌트 단위로 개발을 하면서 의미 없는 div태그로 감싸여진 코드들을 볼 수 있다. 이는 jsx를 사용하면서 return은 두개의 값을 반환 할 수 없어 하나의 최상위 태그를 사용해야 하기 때문이다. 이때 Fragment를 사용하면 의미 없는 태그 사용을 막을 수 있다. 일반적으로 div를 사용하면 이런식으로 보여지게 된다.",
    date: "2022.12.21",
    category: "react",
    link: "React-Fragment-learn",
    element: <ps.ReactFragment />,
  },
  {
    key: 7,
    title: "클립보드를 이용하여 텍스트를 복사하기",
    body: "텍스트를 복사하는 기능을 만들고 싶을 때 클립보드 기능을 이용하면 쉽게 만들 수 있다 이렇게 클립보드API를 이용하면 간단하게 클립보드를 이용한 복사기능을 만들 수 있다. 이때 주의사항이 있는데 클립보드에 엑세스 하면 암호나 신용카드 번호와 같이 중요한 정보에 엑세스 할 수 있는 문제가 생긴다 이와 같은 이유 때문에 http가 없는 임시 서버에서 실험을 할 경우 동작하지 않을 수 있다.",
    date: "2023.02.01",
    category: "javascript",
    link: "ClipboardCopy",
    element: <ps.ClipBoardCopy />,
  },
  {
    key: 8,
    title: "styled-component를 사용해보자",
    body: "react를 처음 공부할 때 html과 js는 한 파일에서 작성하는데 css도 한 파일에서 작성 할 수 있지않을까 란 생각이 들어 찾아보다가 styled-component를 알게 되었다. styled-component는 js in css 로 말 그대로 js파일 내부에 css를 작성한다는 뜻으로 styled-component의 장점으로는 css의 컴포넌트화로 유지보수가 쉬워지고 재사용성이 올라간다. 패키지 설치 사용 방법 설치가 잘 되었다면 사용방법에 대해 알아보자 ",
    date: "2023.02.03",
    category: "styled-component",
    link: "StyledComponent",
    element: <ps.StyledComponent />,
  },
  {
    key: 9,
    title: "styled-component 전역 스타일링에 대해 알아보자",
    body: "이전에 포스트에서 styled-component 사용법에 대해서 다뤘었는데 오늘은 GlobalStyle과 Theme에 대해 알아보겠다.  GolbalStyle 사용방법 간단하게 createGlobalStyle 이라는 함수를 사용해 css를 작성한 후 최상위 컴포넌트에 추가해주면 된다. 이렇게 사용하면 전역으로 css를 설정할 수 있어 불필요하게 중복되는 스타일링을 줄일 수 있다. Theme 사용방법",
    date: "2023.02.05",
    category: "styled-component",
    link: "StyledComponent-GlobleStyle",
    element: <ps.StyledComponentGlobleStyle />,
  },
  {
    key: 10,
    title: "[HTML] Sementic Tag란?",
    body: "Sementic Tag란? 우선 Sementic Tag의 뜻은 의미가 있는 태그라는 뜻이다. 반대로 div와 span태그와 같은 태그는 non-sementic tag라고 한다 그럼 div 태그로 만들 수 있는데 왜 의미가 있는 태그가 필요할까? Sementic Tag 가 필요한 이유 3가지 1. seo ( Search engine optimization ) 마크업을 통해 보다 많은 검색에 노출 시킬 수 있다.",
    date: "2023.02.07",
    category: "html",
    link: "sementic-tag",
    element: <ps.SementicTag />,
  },
  {
    key: 11,
    title: "react-router에 대해서 알아보자",
    body: "react-router란? react-router는 클라이언트 측 라우팅이 가능하게 도와주는 라이브러리다. react-router를 사용하면 간단하게 url을 변경하면서 여러 페이지로 이루어진 어플리케이션을 만들 수 있다. 패키지 설치 사용방법 위에 코드에 대해 설명을 하면 우선 최상위 컴포넌트에서 BrowserRouter로 감싸준후 Route를 Routes로 감싸준다. Route에 path에는 url경로를 element에는 보여주고자 하는 컴포넌트를 넣어준다. ",
    date: "2023.02.09",
    category: "react-router",
    link: "react-router-learn",
    element: <ps.ReactRouterLearn />,
  },
  {
    key: 12,
    title: "display Grid를 배워보자",
    body: "gird는 행과 열이 있는 레이아웃 시스템을 제공한다. 1차원 레이아웃을 지원하는 flex와 다르게 좀 더 복잡한 레이아웃을 위해 grid를 사용할 수 있다. gird는 flex와 같이 Container와 Item이라는 두가지 개념으로 구분되어 있는데 Container는 Item을 감싸는 부모 요소이며 그 안에 Item을 배치 할 수 있다. Grid Container Properties Container를 위한 속성은 아래와 같다.",
    date: "2023.02.11",
    category: "css",
    link: "grid-learn",
    element: <ps.DisplayGridLearn />,
  },
  {
    key: 13,
    title: "REST FUL에 대해서 알아보자",
    body: "RESTful API는 클라이언트와 서버의 통신을 REST형태로 지원하는 API이다 그럼 REST는 무엇일까? REST는 (Representational state transfer)의 약어로 자원을 이름(자원의 표현)으로 구분하여 해당 자원의 상태(정보)를 주고 받는 모든 것을 의미한다. REST는 클라이언트 측에서 URL형태로 Server에 요청을 할 수 있다.",
    date: "2023.02.16",
    category: "network",
    link: "restful-learn",
    element: <ps.Restful />,
  },
  {
    key: 14,
    title: "Axios를 배워보자",
    body: "Axios란? Axios는 Promiss기반 HTTP 클라이언트이다. 간단하게 백엔드랑 통신을 쉽게 해주는 라이브러리이다. 특징으로는 HTTP요청과 응답을 JSON형태로 할 수 있다는 점이다. 사용방법 axios로 백엔드와 통신을 할 때는 get(조회), post(등록및 전송), put(수정), delete(삭제) 이렇게 4가지의 HTTP 메서드를 이용하여 통신할 수 있다. ",
    date: "2023.02.21",
    category: "Front-end",
    link: "axios-learn",
    element: <ps.AxiosLearn />,
  },
  {
    key: 15,
    title: "Jsdoc주석에 대해서 알아보자",
    body: "JSDoc 주석은 JavaScript 코드에 추가되는 문서화 주석이다. 이 주석은 함수, 변수, 객체의 설명, 타입정보 등을 제공할 수 있다. JSDoc 주석 사용법 이와 같이 함수를 호출 할 때 주석를 보여주게 된다. 해당태그를 사용하면 취소선을 그어준다 해당태그를 사용하면 타입을 명시 할 수 있다. 해당태그를 리소스를 참조할 떄 사용할 수 있다. ",
    date: "2023.02.26",
    category: "javascript",
    link: "jsdoc-learn",
    element: <ps.Jsdoc />,
  },
  {
    key: 16,
    title: "팀프로젝트 기록 - 1",
    body: "그동안 클론코딩을 하면서 기본적인 html, css, js 익혔고 이번에는 팀프로젝트에 참여해서 협업을 하는 경험을 하고 싶었다. 그래서 동아리같이 팀 단위로 개발하는 곳 을 알아보던 와중 왁물원이라는 네이버 카페에서 카페회원들 끼리 자체적으로 카페 내부 서비스를 만들어 보고 싶다는 글이 올라와 얼른 신청을 했다.",
    date: "2023.03.06",
    category: "react",
    link: "team-project-chim-1",
    element: <ps.ThemProjectChimONE />,
  },
  {
    key: 17,
    title: "7계층에 대해 알아보자",
    body: "7계층이란? 7계층은 네트워크 통신이 일어나는 과정을 7단계로 나눈 것 을 말한다. 각각 물리층, 데이터링크층, 네트워크층, 전송층, 세션층, 표현층, 가장 상위계층에 속하는 응용층 으로 나뉘고 두 컴퓨터가 네트워크를 형성하여 데이터를 주고 받기 위해서는 7계층이 모두 필요하여 각각의 계층은 독립된 기능을 제공한다",
    date: "2023.03.12",
    category: "Computer Science",
    link: "Layer",
    element: <ps.OSI7Layer />,
  },
  {
    key: 18,
    title: "ci/cd에 대해 알아보자",
    body: "ci/cd에 대해 알아보자 ci/cd는 지속적인 통합, 지속적인 배포라는 뜻을 가지고 있다. 그럼 왜 지속적인 통합과 배포가 필요한가라고 하면 서비스를 배포할 때 마다.  개발자들이 직접 수정, 빌드, 테스트, 배포를 하게 된다면 상당히 많은 시간이 소요된다. 이때 ci/cd를 맞게 작성한다면 빌드, 테스트, 배포를 하는 시간을 크게 줄일 수 있어",
    date: "2023.03.16",
    category: "Computer Science",
    link: "ci-cd-learn",
    element: <ps.CiCdLearn />,
  },
  {
    key: 19,
    title: "Recoil에 대해 알아보자",
    body: "개발을 하다보면 전역 상태 관리라는 말을 한번쯤은 들어봤을거다. 프로젝트의 규모가 커져감에 따라 수많은 state와 props가 점점 복잡해져 이러한 상태를 관리해주는 라이브러리들이 생겼다. 그 후 react에서 Context API라는게 나오긴 했지만 여전히 상태관리 라이브러리를 사용 하고 있다. Recoil란? Recoil은 hook을 사용하고 있는 사람이라면 익숙하게 사용 할 수 있는 장점이 있다. ",
    date: "2023.03.20",
    category: "Front-end",
    link: "recoil-learn",
    element: <ps.RecoilLearn />,
  },
  {
    key: 20,
    title: "HTTP/HTTPS의 개념",
    body: "HTTP(Hypertext Transfer Protocol)는 클라이언트와 서버 간 통신을 위한 통신 규칙이다. 사용자가 웹 사이트에 방문을 하면 자용자 브라우저가 웹 서버에 HTTP요청을 전송하고 웹 서버는 HTTP로 응답한다. HTTP는 네트워크 통신을 작동하게 하는 기본 기술이다. HTTPS(Hypertext Transfer Protocol Secure)는 HTTP의 확장 버젼에 안정성이 더 올라간 버젼인데 HTTPS는 브라우저와 서버가 데이터를 전송하기 전에 안전하고 암호화된 열결을 설정한다. ",
    date: "2023.03.25",
    category: "Computer Science",
    link: "HTTP&HTTPS-learn",
    element: <ps.HTTPAndHTTPSlearn />,
  },
  {
    key: 21,
    title: "npm vs yarn",
    body: "npm npm(Node Package Manager)은 Node.js의 기본 패키지 매니저로 라이브러리와 패키지를 관리하고 설치, 업데이트, 제거 등을 할 수 있다. package.json 파일을 사용해 의존성과 버젼을 관리한다.  yarn은 Facebook에서 만든 패키지 매니저인데 순차적으로 설치하는 npm과 달리 병렬로 설치해 속도 도 더 빠르다. 또 패키지 버젼 관리에 용이한데 npm install을 한다고 해서 모든 개발자가 동일한",
    date: "2023.03.30",
    category: "javascript",
    link: "npm&yarn",
    element: <ps.NpmVsYarn />,
  },
  {
    key: 22,
    title: "package.json에 대해서",
    body: "package.json이란? package.json이란 패키지 매니저로 설치한 모듈들의 의존성을 명세하고 관리하는 파일이다. name, version 패키지의 이름과 버젼을 명세하기 위해 필요한데 몇가지 규직이 존재한다. 이름은 214자 이하여야 한다. 범위가 지정된 패키지의 이름은 점 또는 밑줄로 시작할 수 있다. 범위가 없으면 허용되지 않는다. ",
    date: "2023.04.06",
    category: "javascript",
    link: "package.json-about",
    element: <ps.PackageJson />,
  },
  {
    key: 23,
    title: "Symbol에 대해서",
    body: "Symbol은 ES6에서 추가된 7번째 데이터 타입이다. 심볼은 주로 이름의 충돌 위험이 없는 객체의 프로퍼티 키를 만들기 위해서 사용한다. Symbol은 Symbol()함수를 호출하어 생성한다 이때 생성된 Symbol은 객체가 아니라 변경 불가능한 원시타입의 값이다. 이렇게 보면 생성자 함수로 객체를 생성하는 것처럼 보이지만 Symbol함수는 String, Number, Boolean 생성자와",
    date: "2023.04.11",
    category: "javascript",
    link: "symbol-about",
    element: <ps.SymbolAbout />,
  },
  {
    key: 24,
    title: "자바스크립트 반복문",
    body: "반복문의 종류 for 문 for...in 문 for...of 문 while 문 do...while 문 for 문 for 문은 특정한 조건이 거짓이 될 때 까지 반복한다. for...in 문 for...in 문은 객체의 속성을 열거할 때 유용하게 활용된다. 하지만 일반적인 배열에도 사용이 가능하다.for...of 문 for...of 문은 배열이나 이터러블(iterable) 객체의 각 요소들을 반복적으로 순회하는 데 사용된다.",
    date: "2023.04.15",
    category: "javascript",
    link: "js-loop",
    element: <ps.JsLoop />,
  },
  {
    key: 25,
    title: "React 커스텀 Hook 만들기",
    body: "리엑트를 다룰 때 useState나 useEffect같은 Hook을 많이 사용해 봤을거다. 근데 이 Hook을 개발자가 원하는대로 만드는게 가능하다. 커스텀 훅은 반복되는 로직을 관리하는데 매우 용이하다. 사용방법 커스텀 훅을 만드는 방법은 그렇게 어렵지 않다. 이전에 커스텀 훅을 만들때 지켜야 할 규직이 몇가지 있는데 다음과 같다.",
    date: "2023.04.20",
    category: "react",
    link: "custom-hook",
    element: <ps.CustomHook />,
  },
  {
    key: 26,
    title: "yaml파일 문법",
    body: "yaml은 YAML ain’t markup language의 약어로 마크업 언어가 아닌 데이터에 특화됨 을 보여주는 말이다. json 파일의 상위 버젼이라고 생각할 수 도 있다. 주석을 달 수 없고 json의 중괄호와 대괄호 남발로 코드길이가 질어지게 된다는 단점을 보안하고자 해서 나온 방식이다. 또한 문법을 보면 Python과 매우 유사함을 알 수 있다.",
    date: "2023.04.24",
    category: "yaml",
    link: "yaml-about",
    element: <ps.YamlFileGrammar />,
  },
  {
    key: 27,
    title: "무한 스크롤 구현하기 (Intersection observer API)",
    body: "팀프로젝트를 진행하면서 무한스크롤을 이용해서 게시글들을 보여주기로 했다. 페이지네이션이 아닌 무한 스크롤을 선택한 이유는 모바일 환경 지원이 이유이기도 하다. 무한 스크롤을 만들어 본 적이 없어 어떻게 만들어야 하나 찾아보던 중 세 가지 방법으로 만들 수 있다고 했다. 첫번째는 스크롤 이벤트 헨들러를 이용한 방법이고 두번째는 Debounce 와 Throttle를 이용한 방법 마지막으로 ",
    date: "2023.05.01",
    category: "react",
    link: "Infinite-Scroll",
    element: <ps.InfiniteScroll />,
  },
  {
    key: 28,
    title: "referrer 외부 링크 금지 이미지",
    body: "팀프로젝트를 진행하던 도중 외부에서 불러온 이미지가 로드되지 않고 404를 반환하는 이슈가 있었다. 404를 반환한 이유를 알아보니 네이버에서 이미지를 가져올 때 보안에 관련된 이유로 404를 반환하는 것 이였다. 반환 하는 이유는 Referer 체크로 외부 링크를 금지하여 404를 반환 하는 것이다. 이를 해결 할 수 있는 방법으로는 이미지에 (referrerpolicy='no-referrer')속성을 추가해주면 된다.",
    date: "2023.05.06",
    category: "html",
    link: "referrerpolicy-img",
    element: <ps.referrerpolicyImg />,
  },
  {
    key: 29,
    title: "타입스크립트 타입 종류",
    body: "타입스크립트에 대한 수요가 늘어나 타입스크립트를 공부하면서 정리해보려 한다. 타입스크립트는 타입을 지정해 줌으로써 기존 자바스크립트에서 발생하는 에러를 미리 예방 할 수 있다는 장점이 있다. 타입스크립트 기본타입 Boolean 참/거짓(true/false)에 대한 타입이다 Number 값이 숫자이면 다음과 같이 선언한다.",
    date: "2023.05.09",
    category: "typescript",
    link: "typescript-learn",
    element: <ps.TsTypeLearn />,
  },
  {
    key: 30,
    title: "타입스크립트 인터페이스",
    body: "타입스크립트에서는 인터페이스를 활용해 변수의 타입으로 사용할 수 있다. 인터페이스는 클래스와 비슷한데 클래스와는 다르게 정의만 할 뿐 구현이 되지 않는다는 차이점이 있다. 타입스크립트에서 인터페이스는 상호 간에 정의한 약속 혹은 규칙을 의미한다. 인터페이스는 보통 다음과 같은 범주에 대해 정의할 수 있다. ",
    date: "2023.05.13",
    category: "typescript",
    link: "typescript-interface",
    element: <ps.InterfaceGenericLearn />,
  },
  {
    key: 31,
    title: "타입스크립트 커스텀타입",
    body: "커스텀 타입이란? 타입스크립트에는 커스텀 타입이라는게 있다. 커스텀 타입은 말 그대로 타입을 커스텀 하여 만들 수 있다는 말인데 기존 타입에 새로운 이름을 지정해준다거나 새로운 타입을 선언해주는 것 이 가능하다. 커스텀 타입을 사용하면 보다 강력하게 타입을 지정할 수 있다. 위와 같이 사용하면 잘못된 함수의 사용을 막을 수 있다.",
    date: "2023.05.20",
    category: "typescript",
    link: "typescript-customTypes",
    element: <ps.CustomTypesLearn />,
  },
  {
    key: 32,
    title: "타입스크립트 제너릭",
    body: "제너릭이란? 제너릭이란 타입을 파라미터처럼 사용 할 수 있는걸 의미한다. 제너릭의 장점으로는 다양한 타입에 대한 재사용성이 올라간다는 점이 있다. 위의 코드를 보면 받은 파라미터를 그대로 반환해 주는데 받은 파라미터 타입이 number가 아니라면? 타입별로 함수를 만들어주게 되면 코드의 재사용성도 떨어지고 유지보수도 힘들어진다. 이떄 사용하면 좋은게 제러릭이다. ",
    date: "2023.07.11",
    category: "typescript",
    link: "typescript-Generics",
    element: <ps.GenericsLearn />,
  },
  {
    key: 33,
    title: "npm ERR! Cannot read properties of null (reading 'edgesOut')",
    body: "최근 배포를 하던 와중에 npm ERR! Cannot properties of null (reading) 이런 에러가 발생했다. 문제는? 최신버젼의 styled-components에서 npm i styled-components를 수행하는 동안 생기는 문제였다. 해결방법 V5 사용, npm install styled-components@5.3.10 원사 사용, yarn install styled-components 베타 버전을 사용하려면,npm install styled-components@latest 나의 경우에는 npm install styled-components@latest 를 사용해 해결했다. ",
    date: "2023.07.13",
    category: "Front-end",
    link: "npm-ERR-Cannot-read-properties-of-null-reading-edgesOut",
    element: <ps.ErrEdgesOut />,
  },
  {
    key: 34,
    title: "react에서 addEventListener와 state",
    body: "최근 개발을 하다 window.addEventListener로 호출한 함수 내에서 state값이 초기 값 그대로 읽히는 경우가 있었다. 아래와 같이 코드를 작성 했을 떄 state값은 계속 변경 되지만 console.log()로 state값을 읽을땐 초기값만 출력이 된다. 이렇게 동작하는 원인이 무엇일까? 이렇게 동작하는 이유는 이벤트 핸들러 함수는 비동기적으로 실행되기 때문에 ",
    date: "2023.07.18",
    category: "react",
    link: "addEventListener&state",
    element: <ps.EventListenerState />,
  },
  {
    key: 35,
    title: "코드 포멧팅 prettier",
    body: "코드 포멧터 Prettier 여러 사람들과 개발을 하게되면 각자 개발 습관에 따라 세미콜론(;), 줄간격, 행 등이 각각이 달라 코드가 뒤죽박죽이 되는 상황이 생기게 됩니다. 이때 Prettier를 사용하게 되면 정해진 규칙에 따라 모맷팅 해주기 때문에 수고 없이 코드를 짜기만 하면 됩니다. 사용방법 설치가 끝났다면 .prettierrc.json 파일을 만들어 관리해줄 수 있다.",
    date: "2023.07.27",
    category: "Front-end",
    link: "js-prettier",
    element: <ps.CodePrettier />,
  },
  {
    key: 36,
    title: "타입 추론",
    body: "타입추론 타입스크립트에서는 명시적인 타입 표시가 없을때 타입에 대한 정보를 제공한다. 일반적인 뿐만이 아니라 구조분해 코드에서도 타입추론이 되어 유용하게 사용 할 수 있다. 타입추론이 이렇게 유용하다면 타입을 적어주지 않아도 될까? 그렇다면 타입스크립트를 사용하는 의미가 없어진다고 생각한다. 그럼 타입추론을 사용할 때와 ",
    date: "2023.08.15",
    category: "typescript",
    link: "Type-Inference",
    element: <ps.TypeInference />,
  },
  {
    key: 37,
    title: "TypeScript 환경에서 createContext 사용하기",
    body: "최근 타입스크립트 환경에서 creactContext를 사용하다 아래와 같은 에러가 발생해 createContext 사용방법과 해결방법을 정리해보려 한다. creactContext 사용방법 기본적으로 creactContext를 생성해주면 된다. 그 이후 구성 요소를 context.Provider 로 래핑 해준뒤 useContext로 호출해 사용할 수 있다. 만약 기본값이 없다면 null으로 지정해주면된다. 여기서 문제가 발생했는데 .Provider로 래핑해준 후 사용해주려 하니 위와 같은 에러가 발생했다.",
    date: "2023.08.16",
    category: "typescript",
    link: "typescript-context-api",
    element: <ps.CreateContextErr />,
  },
  {
    key: 38,
    title: "팀프로젝트 후기",
    body: "팀프로젝트 회고록 최근 침플래닛 이라는 팀프로젝트가 성공적으로 마무리 되어 처음으로 회고록을 작성해 보려 한다. 이번 프로젝트를 진행하면서 개인적으로 많은 성장을 이뤄냈다고 생각해 정리해보도록 하겠다. 내가 프로젝트에 합류 했던 당시 이미 모든 팀원이 구해져 있던 상황이였다 기획 : 1명 백엔드 : 3명 프론트 : 2명 기획 : 1명 일러스트 : 1명 웹 디자이너 : 1명 그래픽 디자이너 : 1명 으로 이루어졌다. 합류한후에 인수인계 겸 회의를 진행 했는데 내 걱정과는 다르게 자유롭고 재미있는 분위기에서 진행되는 ",
    date: "2023.08.25",
    category: "react",
    link: "team-project-chim-2",
    element: <ps.ThemProjectChimTwo />,
  },
  {
    key: 39,
    title: "discord.js로 봇을 만들어보자",
    body: "프로젝트 소개 메이플스토리라는 게임을 하다가 디스코드로 내 캐릭터에 대한 정보를 볼 수 있으면 편하겠다는 생각이 들었고, 친구와 이야기 하다 너무 재미있을 것 같아 당장 만들어보았다. discord.js가 너무 잘 만들어져 있어 생각보다 간단하게 만들 수 있었다. 프로젝트 사용한 라이브러리 axios를 이용해 HTTP 요청으로 웹에 대한 정보를 가져와 cheerio를 이용해 웹에 대한 데이터를 쉽게 가공해 원하는 정보를 가져올 수 있도록 했다. ",
    date: "2023.09.08",
    category: "node.js",
    link: "create-discord-bot-1",
    element: <ps.CreateDiscordBotOne />,
  },
  {
    key: 40,
    title: "프론트엔드 기술면접 정리 - 1",
    body: "앞으로의 기술면접을 대비해 그동안 공부했던걸 한번 정리해보려 한다. Web 브라우저 렌더링 순서 1. 주소창에 입력된 주소를 통해 서버를 찾아간다. 2. 이후 DNS가 연결해줄 곳을 찾는다 3. 서버에서 HTML 파일을 클라이언트로 보내준다 4. HTML문서는 파싱되어 DOM을 생성한다.(객체 형식) 5. 중간에 CSS를 로드하는 link혹은 style 태그를 만나면 HTML파싱 중지후 CSS파싱을 시작한다",
    date: "2023.09.21",
    category: "Cs",
    link: "DeveloperInterviewOne",
    element: <ps.DeveloperInterviewOne />,
  },
  {
    key: 41,
    title: "프론트엔드 기술면접 정리 - 2",
    body: "Http HTTP 통신이란? (Hypertext Transfer Protocol) 웹 프로토콜 중에 하나. 인터넷으로 데이터를 주고받을 수 있는 통긴규약. Request와 Reponse로 이뤄져 있음. Http와 Https의 차이 Http - 암호화 X - 빠름 Https - 보안, 암호화 O - 설치 및 인증서 유지에 대한 비용이 듦 - 중간에 정보를 탈취해도 볼 수 없도록 암호화를 지원한다. CORS CORS(Cross-Origin Resource Sharing)란?",
    date: "2023.09.27",
    category: "Cs",
    link: "DeveloperInterviewTwo",
    element: <ps.DeveloperInterviewTwo />,
  },
  {
    key: 42,
    title: "discord.js로 봇을 만들어보자 - 2",
    body: "여기에는 문제점이 있었는데 크롤링을 인기도 랭킹에서 하다보니 인기도가 0인 캐릭터들은 검색이 되지 않는 문제가 있었다. 이 문제를 해결하기 위해선 종합랭킹 에서 크롤링을 해와야하는데 여기는 일반월드와 리부트월드가 나눠져 있어서 조건문을 통해 일반월드 검색 결과가 없다면 리부트월드를 검색 하도록 변경했다. 이렇게 가져온 데이터를 이전보다 더 잘 보여주고 싶어서 찾아보니 Embeds라는 기능이",
    date: "2023.10.05",
    category: "node.js",
    link: "create-discord-bot-2",
    element: <ps.CreateDiscordBotTwo />,
  },
  {
    key: 43,
    title: "discord.js로 봇을 만들어보자 - 3",
    body: "디스코드 봇 호스팅하기 이번엔 만들었던 디스코드 봇을 aws에 호스팅 해보도록 하겠다. 시작  1. 우선 아마존 aws에 계정을 만들고 카드 등록까지 해준다 2. 인스턴스 시작 버튼을 눌러 인스턴스를 생성해준다. 2. EC2 인스턴스 이름을 적고 OS를 선택해준다. (나는 Ubuntu를 선택했다.) 3. 그리고 가장 중요한 키를 생성해준다. 이건 잃어버리면 안 되니 백업을 해준 후 인스턴스 시작을 해준다. ",
    date: "2023.10.25",
    category: "node.js",
    link: "create-discord-bot-3",
    element: <ps.CreateDiscordBotThree />,
  },
  {
    key: 44,
    title: "node 버전관리 nvm",
    body: "NVM 모듈 node를 사용하다보면 개발환경에 따라 버전을 변경해야하는 상황이 오게 된다. 이때 nvm을 사용한다면 편리하게 버전을 변경하며 사용할 수 있다. NVM 설치 여기에 있는 링크에 들어가서 nvm-setup.exe나 nvm-setup.zip 파일을 받아 설치를 해주면 된다. NVM 사용법 설치를 해주었다면 사용법은 간단하다. nvm -v // nvm 버젼 확인 nvm current // 현재 사용중인  노드버전 확인",
    date: "2024.01.26",
    category: "node.js",
    link: "how-to-use-nvm",
    element: <ps.HowToUseNvm />,
  },
  {
    key: 43,
    title: "discord.js로 봇을 만들어보자 - 4",
    body: "얼마전에 메이플 공식 api가 업데이트 됐다고 해서 디스코드 봇을 업데이트하기로 했다. 그래서 메이플 공식 api사용법과 이번에 추가한 내용을 블로그에 담으려 한다. api Key 발급 여기 공식 api 주소에 들어가 로그인을 한 뒤 어플리케이션 등록을 진행하면 된다. 여기에서 서비스 단계인지 출시 단계인지 선택하는 항목이 있는데 그 둘의 차이점은 초당 최대 허용량과 일일 최대 허용량으로 나뉜다.",
    date: "2024.02.15",
    category: "node.js",
    link: "create-discord-bot-4",
    element: <ps.CreateDiscordBotFour />,
  },
];

export default content;

/* 
  {
    key: ,
    title: "",
    body: "",
    date: "",
    category: "",
    link: "",
    element: <ps.NpmVsYarn />,
  },
    {
    key: 30,
    title: "팀프로젝트 기록 - 2",
    body: "",
    date: "2023.04.06",
    category: "",
    link: "team-project-chim-2",
    element: <ps.ThemProjectChimTwo />,
  },
*/
